### ISSUE TITLE
Synch double multiplex

### ISSUE THREAD

**Issue by hattom** [yDgunz/gunswap#2]
I don't know whether or not it's supposed to be supported, but I'm fairly sure that it shouldn't fair due to a state repeating problem.

([42],[2]) doesn't work: Pattern took more than 500 beats to repeat states
([42],2) does work

**Comment by yDgunz** [comment]
Found the issue here as well, looks like multiplexes in the right hand component of the sync toss are screwing up. So ([42],2) is fine but (2,[42]) is not. An issue with my siteswap parsing code. 

You've probably also noticed that the multiplex tosses look weird in the dwell path, like one ball is floating. Gotta work on that...

Hope you like the animator!
